### ISSUE TITLE
NavMesh Surface2d Component missing

### ISSUE THREAD

**Issue by Dragoonian** [h8man/NavMeshPlus#118]
I've downloaded NavMeshPlus to use in my unity project, however the component I need (NavMesh Surface2d) is missing from it. I looked on the scripts on the github page and its not there either. Was this replaced by something? Thanks

**Comment by h8man** [comment]
There some updates and changes right now, so project is not very stable, but here is new instruction:

Copy repo into your Asset folder (or install as a package).
Create Empty Object in scene root.
Add "Navigation Surface" component to Empty Object and add NavMeshCollecSources2d component after.
Click Rotate Surface to XY (to face surface toward standard 2d camera x-90;y0;z0)
Add "Navigation Modifier" component to scene objects obstacles, override the area.
In "Navigation Surface" hit Bake.

**Comment by LeonardA-L** [comment]
Hi, I second the "not very stable". The recent updates in the last few dates did completely break the navmesh baking process (no navmesh is created when baking, even with the new instructions here, the instructions on the wiki, or in the Readme).
No error log shown, so I can't help much.

Reverting to commit https://github.com/h8man/NavMeshPlus/tree/4a5aec0a091d2932d9195de2c247b6c052c9cef7 fixes the issue, so for now I'll keep using that.

This is a terrific tool otherwise, so good luck!
