### ISSUE TITLE
NavMesh Modifier Volume not working

### ISSUE THREAD

**Issue by Scheshi** [h8man/NavMeshPlus#194]
![image](https://github.com/h8man/NavMeshPlus/assets/47576867/05c65f27-2089-48f8-97e9-8229cb0a5a0b)

**Comment by h8man** [comment]
Just tested. https://github.com/h8man/RedHotSweetPepper/tree/master/Assets/Scenes/SampleSceneVolume

What exact case doesn't work?

**Comment by snarlynarwhal** [comment]
Hi, I'm having issues with NavMeshModifierVolume as well. I opened the sample scene and searched for "t:NavMeshModifierVolume" but not find any components.

**Comment by h8man** [comment]
@snarlynarwhal It has setup for volume to play around.
In what scenario it doesn't work?
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/90e299e8-df1b-4ad1-937c-16a2209db843)

**Comment by snarlynarwhal** [comment]
Okay, my scene does not have that game object. I tested on master. What branch are you on?

**Comment by h8man** [comment]
@snarlynarwhal I used master branch
1. Open "SampleSceneVolume"
2. Add empty Object
3. Add NavigationModifierVolume component, set "Not Walkable"
4. Select NavMesh and Bake new mesh
Expected Result: new volume excluded from mesh

So share your setup, scene and mesh collect type

**Comment by snarlynarwhal** [comment]
Apologies, that does indeed work — I misunderstood the purpose of NavigationModifierVolume component. I thought it was to update the mesh without having to rebake the entire mesh. I had assumed that on enable/awake it'd update the graph in that particular volume. I have a game where projectiles spawn temporary obstacles, which get added and removed frequently. I want to avoid needing to rebake constantly since of course that causes lag. Is `NavMeshBuilder.UpdateNavMeshDataAsync` my best option for a lot of frequent updates at runtime?

**Comment by h8man** [comment]
Yes/No

If you supply the same sources collection is the same order it will greatly increase performance (it is stated somewhere in Unity documentation). You can utilize Collection Cache component to get that collection and update manually.

There is sample in https://github.com/h8man/RedHotSweetPepper

**Comment by snarlynarwhal** [comment]
That seems to work well for me, thank you!
