### ISSUE TITLE
NavMeshPlus.Components.Editors.NavMeshSurfaceEditor.RenderBoxGizmoSelected

### ISSUE THREAD

**Issue by ConanGentleman** [h8man/NavMeshPlus#207]
I also see following error like  [https://github.com/h8man/NavMeshPlus/issues/200](https://github.com/h8man/NavMeshPlus/issues/200) ,but it doesn't work.
`
NullReferenceException: Object reference not set to an instance of an object
NavMeshPlus.Components.Editors.NavMeshSurfaceEditor.RenderBoxGizmoSelected (NavMeshPlus.Components.NavMeshSurface navSurface, UnityEditor.GizmoType gizmoType) (at Packages/NavMeshPlus/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:310)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
`
version: 2021.3.14f1.

**Comment by h8man** [comment]
I will add code for unity 2021.3.14f1 on this weekend. Now it only works in 2022.3

**Comment by dre4mer12345** [comment]
is it possible to also add an editor exception to correct [Build error: CS0426: The type name ‘SyncTile’ does not exist in the type ‘Tilemap'](https://discussions.unity.com/t/build-error-cs0426-the-type-name-synctile-does-not-exist-in-the-type-tilemap/876593)

for unity 2021.3 you have to pull the package out of cache and fix it in order to do builds.

**Comment by h8man** [comment]
https://github.com/h8man/NavMeshPlus/commit/ea4ded6bbbd41641b8d0b1d2dd307dcad59868ce

**Comment by h8man** [comment]
@ConanGentleman please check if it work with 2021.3.14f1.

**Comment by h8man** [comment]
no reply
