### ISSUE TITLE
Z coordinate of tiles is ignored

### ISSUE THREAD

**Issue by subGlitch** [h8man/NavMeshPlus#26]
Looks like you completely ignoring Z coordinate of tiles.

I'm making a top-down 2D game. Despite it's in 2D, it's in Top-down Oblique projection, so it uses Z ordering for character to be able to stand behind a rock or behind a tree, for example. So, position of each tile is = Vector3Int( x, y, y ). But NavMeshBuilder2d.CollectTileSources() method iterates only through X and Y axes.

I managed to fix it by adding iteration over Z axis in CollectTileSources() method and setting Override Vector to (1, 1, 0). I don't understand what Override Vector is. It was just a guess. But it worked.

I hope you will add iteration over Z axis, so I can use your great tool without my own modifications.
Cheers

**Comment by h8man** [comment]
Hi,

Setting Override Vector (1, 1, 0) will convert all Z values to zero, so that any tilemap will be flattened for NavMesh.
That was made for your scenario, where you want to utilize camera Z sorting or any other 3D feature.

its used in coordinates calculus:
`Matrix4x4.Translate(Vector3.Scale(tilemap.GetCellCenterWorld(vec3int),builder.overrideVector)) * tilemap.GetTransformMatrix(vec3int);`

NavMesh Plus was made with 2D plain in mind. I made bare minimum, and not in extensive or extensible way.
Use cases can be discussed in https://forum.unity.com/threads/2d-navmesh-pathfinding.503596/page-5#post-6084279
