### ISSUE TITLE
It sometime bakes wrong.

### ISSUE THREAD

**Issue by mjshin82** [h8man/NavMeshPlus#60]
It looks fine.
![image](https://user-images.githubusercontent.com/22926212/146658160-3639f6ef-95c3-4cf4-9182-1fe3313d74f4.png)

I can not walk to the upside, because
![image](https://user-images.githubusercontent.com/22926212/146658161-a528c347-b996-4674-8684-d633144747b2.png)
When I scale up the scene, there is some blank area.

![image](https://user-images.githubusercontent.com/22926212/146658228-0ea850f5-c702-43db-b8d1-496ff72e688f.png)

**Comment by h8man** [comment]
Hello,

I see that sprites are very details, it may cause problems for mavmesh bake.

There are many options that you should try:

1) Reduce mesh Voxel size https://docs.unity3d.com/Manual/nav-AdvancedSettings.html
2) Use colliders as a source instead of sprite shapes https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#geometry-options
3) Threat every obstacle as square tile https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#override-by _(If we remove the prefab and leave the override option, all tiles will be considered as squares.)_
