### ISSUE TITLE
Agent's Z position is not zero

### ISSUE THREAD

**Issue by noakishere** [h8man/NavMeshPlus#62]
Hi I have a quick question, why is the agent's Z axis not zero? 

I'm using this for a 2d topdown strategy game and when agents get to a specific point, it seems as if the distance between the agent and the destination is never truly 0. Could you please provide some more explanation on this behaviour? 

I have already put the agent.updateRotation to false.

Example screenshot: 
![image](https://user-images.githubusercontent.com/54872856/148840025-fc6d3b30-d7bf-40e1-a586-962a190cf55a.png)

Thanks in advance!

**Comment by h8man** [comment]
Hello @noakishere 

NavMesh Agent is a Unity component, and it cannot be overridden. So instead of overriding agent position you can override object position and cut of Z oscillations.

I don't have any other solution as creating custom Agent is huge amount of work.

You can try https://arongranberg.com/astar/
* Source Code Included - YES
* Local avoidance - NO
But at least you can override things.

**Comment by noakishere** [comment]
Hello,

Thanks so much for your answer! And also thanks for the great tool that you've developed.

Best,

**Comment by CiriousJoker** [comment]
One addition to this solution (after countless hours of debugging):

Set the initial transform position & rotation to 0/0/0 & 0/0/0, otherwise the entity spawns at 0/0/-1 & -90/0/0 (this being invisible). 

This needs to be done in `Awake()`, `Start()` will **not** work.
