### ISSUE TITLE
How to  change NavmehAgent offset

### ISSUE THREAD

**Issue by sherlock221** [h8man/NavMeshPlus#65]
Hi , I am woking with NavmehAgent now and I am trouble with a question.
Now I see that NavmehAgent use the pivot of the sprite as the center point, but I wander how to change the center point to the exact position I want.
Just like I marked in the picture, I want to change the position from the "default" point to the "here"point.
I don't know if I explain the question clear, I really hope to see your respone, the problem is making me crazy.
By the way, I am very lucky to find such a amazing plus that you created, it has helped me solve many problems, thanks!
![image](https://user-images.githubusercontent.com/5842676/154994338-dc9dcda0-d524-40cd-9882-951dabb234a9.png)

**Comment by h8man** [comment]
Hello @sherlock221

NavMesh `Agent` is `unity` component, and it doesn't have left-right offset, only height.
I think this is by design, as pivot point means "turning pint", an axis on which `agent` and all `game object` turns.

So offset should be applied to sprite, as it is a presentation layer. So you need to change pivot point for `sprite`, or add child `gameobject` with `sprite renderer` where you can apply offset.

**Comment by sherlock221** [comment]
Thanks for the feedback!
